### ISSUE TITLE
Deactivate findable DOIs on deletion

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/gbif-doi#21]
As per title
Links: [DataCite DOI states](https://support.datacite.org/docs/doi-states), [DOI deactivation](https://support.datacite.org/docs/can-i-delete-or-change-my-dois)

**Comment by dnoesgaard** [comment]
Are you referring to when someone deletes a dataset that we should change the status with Datacite from Findable -> Registered?

**Comment by timrobertson100** [comment]
>Are you referring to when someone deletes a dataset that we should change the status with Datacite from Findable -> Registered?

Yes
