### ISSUE TITLE
mint DOIs for pre-Feb 2015 downloads

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-doi#3]
from @dnoesgaard in https://github.com/gbif/portal-feedback/issues/696

**We should be able to somehow mint DOIs for pre-Feb 2015 downloads**

**Comment by timrobertson100** [comment]
Can you elaborate on why though please? Do we have real cases where people would update their citations?

**Comment by MortenHofft** [comment]
Yes Daniel came down the other day based on a request where someone wanted to "do the right thing" and quote with DOI, but there wasn't one on the download because it predated that practice.

**Comment by dnoesgaard** [comment]
For the record, this isn't necessarily about "updating" citations. Research takes time (clearly) and some of these studies coming out now are based on downloads from 2-3 years ago. As I mentioned, we try so hard to get people to follow these citation guidelines, it would be a shame not to be able to help those who are indeed trying to comply.

**Comment by MattBlissett** [comment]
I've been looking at DOI registration recently, as there have been other issues.

We have 96,000 older downloads without a DOI. Is it worth registering all of them, or just some, or only on-demand?

**Comment by dnoesgaard** [comment]
I would be fine with a workflow that would allow registering a download ad-hoc, as the demand has been limited. However, it may be simpler in terms of maintenance to just do them all in one go.

**Comment by dschigel** [comment]
There is a still a small but steady % of data uses with pre-2015 downloads. I am not sure though how realistic is to alert those who made those downloads that they now have a DOI, or, as @dnoesgaard suggests, an option to have a DOI. Not 96K e-mails obviously, but will e.g. a news item bring us at least one DOI citation from before 2015 times? I am not sure, and trying to be pragmatic I'd say the gains are not worth the effort.  I am not considering PR benefits of the move here.

**Comment by MattBlissett** [comment]
OK. For the moment then, I will generate DOIs as required for any older download.

If it becomes more than one or two a month, I'll document the process so the helpdesk can do this.

**Comment by MattBlissett** [comment]
Just email me.

**Comment by MattBlissett** [comment]
I've committed scripts to Git, but I don't expect anyone but me to use them. I'll continue to mint the DOIs as required.
