### ISSUE TITLE
Use of 10.5072 prefix for test deprecated

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-doi#5]
From https://github.com/gbif/registry/issues/65

Datacite is implementing [some changes for testing](https://blog.datacite.org/making-testing-simpler/), including discontinuing the 10.5072 prefix.

@dnoesgaard, how did you find out about this? I'm subscribed to their mailing list updates, but they haven't sent anything about this.

**Comment by dnoesgaard** [comment]
Their blog.

**Comment by dnoesgaard** [comment]
(Perhaps another good example of why it might make sense for us to become members of Datacite ourselves?)

**Comment by dnoesgaard** [comment]
Test prefix 10.5072 will be retired officially 1 June 2019.

All testing should be done against the DataCite test environment: https://test.datacite.org/

(I have the credentials)
