### ISSUE TITLE
DOI registration inconsistencies

### ISSUE THREAD

**Issue by fmendezh** [gbif/gbif-doi#7]
Recent changes to Datacite APIs have produced a series of unexpected results while registering, reserving and deleting DOIs. Those issues have been reported by @MattBlissett 
- [https://github.com/datacite/poodle/issues/10](https://github.com/datacite/poodle/issues/10)
- [https://github.com/datacite/poodle/issues/7](https://github.com/datacite/poodle/issues/7)
 The DOI library needs to accommodate this new behavior to avoid errors and inconsistencies, in general, seems that Datacite follows does not reflect immediate changes in the datastores that backed different APIs.
This blog [https://blog.datacite.org/the-datacite-api-landscape/](https://blog.datacite.org/the-datacite-api-landscape/) suggests that even though Datacite will continue supporting the MDS API, its recent efforts were directed to enrich the MDS API.

Suggestions to explore:
-  Validate if the REST API shows the same behavior as the MDS API (currently being used by this library) and estimate the effort of modifying this library to use the REST API
- Keep using the MDS API, refactor this library and fix the failing test cases (see [https://builds.gbif.org/job/gbif-doi/103/testReport/](https://builds.gbif.org/job/gbif-doi/103/testReport/))

**Comment by mike-podolskiy90** [comment]
MDS is not supporting anymore
